services:
  apriniageosat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Only use port 8000, avoid port 80 conflict
    environment:
      - NODE_ENV=production
      - PORT=8000
      - RUNTIME_PHASE=true  # Indicate this is runtime, not build time
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:GtcCg1mKmrmEfgJLwSqQNlnESslWmEySQWrNHAmAis@apriniageosat-postgres:5432/geosatsolusindo}
      - POSTGRES_DB=${POSTGRES_DB:-geosatsolusindo}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-GtcCg1mKmrmEfgJLwSqQNlnESslWmEySQWrNHAmAis}
      - REDIS_URL=${REDIS_URL:-redis://apriniageosat-redis:6379}
      - NEXT_PUBLIC_MEILISEARCH_HOST=${NEXT_PUBLIC_MEILISEARCH_HOST:-http://apriniageosat-meilisearch:7700}
      - NEXT_PUBLIC_MEILISEARCH_API_KEY=${NEXT_PUBLIC_MEILISEARCH_API_KEY:-GtcCg1mKmrmEfgJLwSqQN+lnESslWmEySQWrNHAmAis}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-GtcCg1mKmrmEfgJLwSqQN+lnESslWmEySQWrNHAmAis}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-DkM0Yfqiqb/splFsII6k3ggH884sWKkFuSfhR2oUNzs}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://apriniageosat.co.id}
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    depends_on:
      - apriniageosat-postgres
      - apriniageosat-redis
      - apriniageosat-meilisearch
    networks:
      - app-network

  apriniageosat-postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-geosatsolusindo}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-GtcCg1mKmrmEfgJLwSqQNlnESslWmEySQWrNHAmAis}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  apriniageosat-redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network

  apriniageosat-meilisearch:
    image: getmeili/meilisearch:v1.5
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-GtcCg1mKmrmEfgJLwSqQN+lnESslWmEySQWrNHAmAis}
      - MEILI_ENV=production
    volumes:
      - meilisearch_data:/meili_data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  meilisearch_data:

networks:
  app-network:
    driver: bridge